### ISSUE TITLE
FX GBP:USD and aviation fuel cost

### ISSUE THREAD

**Issue by taverham** [flybeplc/deal#1]
12 nov 18 $1 = £0.77804
jan11  19 $1 = £0.77809     [ The exchange rate for aviation fuel costs are unchanged]
 Nov 18 av $1.95 per gallon
7 Jan 19      $1.71 per gallon  [ Fuel costs have fallen 12%}

**Comment by flybeplc** [comment]
Thanks @taverham do you have a url or source we could link to? 

If you could take a screenshot of a graph from a website like investing.com or others that would be fantastic as nobody can dispute that then so long as the scale isn't biased.

Do we know if they're working with any other currencies?

**Comment by taverham** [comment]
Jack, herewith url
https://www.indexmundi.com/commodities/?commodity=jet-fuel
 I used the table part way down the pag as Nov data and spot price at top.
WRT currencies , my guess is [ excluding fuel ] they will have 90% +
income  and costs in GBP , maybe a few euros etc . Aviation fuel is priced
in usd on the graphs , like most commodities , and purchased in USD the
hedging they refer to is likely to offset that. I got a bit anal and tried
to find euro prices but the data was not available and in the end decided
that the general price movement down was sufficient to refute the statement
and in any event with hedging levels almost irrelevant.
With all of this we have to keep the arguements simple but have the data in
the background if challenged I think you will agree.
p.s are you a software writer?

**Comment by flybeplc** [comment]
Can cast my hand to it sufficiently ;) Ok @taverham updated, is that you had in mind? It would be great we could construct a graph to show the resulting AV1 price taking into account the FX rate.

**Comment by taverham** [comment]
Jack, a graph would be nice but given all the other avenues we need to
pursue do we have time.
Would appreciate your feedback on my latest thoughts on how I am going to
enhance my fca complaint , but also with class action in mind if I can get
a lawyer interested.
So the plan is to produce a number of headings which are;
1. Misleading, incomplete or potential missing RNS statements.
2. Misleading statements ref company finances
3.Actions of BOD which may be outside company law and/or  listing rules
4. Potential Conflicts of Interest [not got anything here except hope that
COW has airfrance shares]
5. Miscellaneous [nothing here yet]
Then attach numbers to each box on the timeline so that I can reference
those documents in my narrative.
What do you think?
Regards,
Andrew M.

**Comment by flybeplc** [comment]
@taverham best to email me (flybe@execs.com) to discuss this one further.  In the meantime I'll close this issue now that we have the FX and AVF costs in.

**Comment by taverham** [comment]
Jack, I hate to ask for more but anychance the timeline could be extended
to include the £2.8m sale of this week?
Regards,
Andrew M.
