### ISSUE TITLE
CFO Nov 14 - appointment of evercore

### ISSUE THREAD

**Issue by taverham** [flybeplc/deal#3]
We have the comment to the effect 'wondering why the cfo could not do the evercore job' . I actually think advisors are always employed in transactions of this size, for their skill and expertise . They are there to ensure the company, i.e the shareholders get the best deal possible [lol] ! However the key failure by the CFO is the cost of the advisors and effect on cash flows. So I would like the comment amended to something like ' Did the CFO review the cash flow projections in advance of advisor appointments recognising the ir costs and payment terms'.

**Comment by flybeplc** [comment]
Good point, that's a great unbiased way to put it.  Updated.
