### ISSUE TITLE
Leaking of price sensitive information

### ISSUE THREAD

**Issue by taverham** [flybeplc/deal#4]
Mark Kleinwort of Sky news broadcast the sale news on 10 Jan at 850pm when nasdaq was still trading . Clearly there was a leak of price sensitive information that the regulatory authorities should investigate.

**Comment by flybeplc** [comment]
Do we have a link for this?  If you can screenshot and attach here that would great.

**Comment by taverham** [comment]
Jack, I do not have one but one of the BB contributors got it from his
twitter , i think  and it was on the BB , I think. I am drafting my 'FCA
letter just now.
Regards,
Andrew M.

**Comment by flybeplc** [comment]
great, update made, timings seem to check out unless there was an earlier tweet that I couldn't find.  Did you get my previous email?  Had account blocked by 1&1 so had to change email: flybeplc@protonmail.com

Will close this issue, feel free to reopen if you have any luck finding an earlier posting.

**Comment by taverham** [comment]
Jack, yes I got your earlier email and thanks for the support. BTW on page
4 of the half year results they show an even higher percentage of hedging
for h2 , which I am using in my text. [ I figured out that over the 6
months the hedging was higher than over 12 months]. You could update the
time line , if you have time! BTW my other half is getting a bit fed up
with my focus here !!
ATB ,
Thanks,
Andrew M

**Comment by taverham** [comment]
Jack, the mark K tweet that is dynamite is the 850 pm on 10 Jan - if it
exists - did you not find it? Has it been deleted?
Regards,
Andrew

**Comment by taverham** [comment]
Jack herewith screen shot suggesting leak the day before at 1247 pm.
[image: image.png]
