### ISSUE TITLE
Typos and amends to consider

### ISSUE THREAD

**Issue by taverham** [flybeplc/deal#5]
Jack, my comments on latest version for your consideration bearing in mind accuracy is key,
13.1 ! or 2 year graphs for oil and usd cover relevant period and cow tenure
15.2 Typo in last sentance 'the ir ' has space.
21.1 The contractors pulled out so BOD had no choice but to take on these people. might have added to their financial woes, so suggest we remove last comments that look like this was wreckless expansion.
24.1 How do we know BOD unaware - that company could have been put forward for the dd . suggest we remove.
32 .1 This weeks rns ref the 2.8m sale could usefully be added.
Best regards, Andrew.

**Comment by flybeplc** [comment]
21.1 "no choice but to take on these people." was that a contractual agreement or goodwill?

24.1 "Owners of Flybe" i.e. the share holders, but yes we don't know if the BOD were unaware. will remove.

32.1 do you mean for A37 "updated offer"?

**Comment by taverham** [comment]
Jack,
21.1 no choice because the planes have to fly and need maintance daily - my
interpretation/guess because  of a practical need.
32.1 yes - done now.
Thanks,
Andrew

**Comment by taverham** [comment]
Jack,thought I would send this rather than BB , but in the Timeline , ref
the sky part , you say 'one can only conclude' that is an opinion. I
actually think it was just to complete the story as to who the consortium
was. I am not sure of the relevance of all the stuff from that point on in
the box.
BTW, i am going to send FCA an amendment to my letter ref the class 1 stuff.
ATB
Andrew ,
