### ISSUE TITLE
Missing previous disclaimer on the title page stating this is not an official Flybe site etc

### ISSUE THREAD

**Issue by spring-at** [flybeplc/deal#6]
2 simple points recommending legal caution required here... 

(a) There used to be a disclaimer in earlier versions on the opening page stating this is not an official site of Flybe or any other parties mentioned in the document. This is missing in the version released 23 Jan 2019. I would suggest that a disclaimer be reinstated. Else entities mentioned in the document may take legal action to have the site taken down and/or pursue legal redress. 

![image](https://user-images.githubusercontent.com/46891772/51606171-13458280-1f09-11e9-9f0c-9dcff0a9456c.png)

(b) Similarly, it may be wise to remove the specific reference to cancer on the slot for Mr Jack Walker, as it could receive similar action from his family and associates.  

Replace  'In 2000 holding the post of JEA Chairman, Jack Walker dies from cancer.'
with        'In 2000 holding the post of JEA Chairman, sadly Jack Walker dies from illness.'

**Comment by flybeplc** [comment]
Thanks @spring-at Also updated the the heading of A2 to instead place emphasis the trust being the main shareholder.
